name: "aider-chat-action"
description: "Easiest way to run Aider in your GitHub Actions workflow"
inputs:
  openai_api_key:
    description: "OpenAI API Key"
    default: ""
    required: false
  anthropic_api_key:
    description: "Anthropic API Key"
    default: ""
    required: false
  gemini_api_key:
    description: "Gemini API Key"
    default: ""
    required: false
  groq_api_key:
    description: "Groq API Key"
    default: ""
    required: false
  cohere_api_key:
    description: "Cohere API Key"
    default: ""
    required: false
  deepseek_api_key:
    description: "Deepseek API Key"
    default: ""
    required: false
  openrouter_api_key:
    description: "OpenRouter API Key"
    default: ""
    required: false
  model:
    description: "Model to use for Aider"
    default: "gpt-4-1106-preview"
    required: false
  branch:
    description: "Branch to run Aider on"
    default: "main"
    required: false
  aider_args_list:
    description: "JSON array of Aider commands to run sequentially (e.g. '[\"--yes --message 'Fix bug'\", \"--yes --message 'Add tests'\"]')"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
    GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
    GROQ_API_KEY: ${{ inputs.groq_api_key }}
    COHERE_API_KEY: ${{ inputs.cohere_api_key }}
    DEEPSEEK_API_KEY: ${{ inputs.deepseek_api_key }}
    OPENROUTER_API_KEY: ${{ inputs.openrouter_api_key }}
    FEATURE_REF: ${{ inputs.branch }}
    MODEL: ${{ inputs.model }}
    AIDER_ARGS_LIST: ${{ inputs.aider_args_list }}

branding:
  icon: "cpu"
  color: "white"
